jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install twine pytest && twine upload
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - python/test:
          args: '--dev'
          pip-dependency-file: requirements_dev.txt
          pkg-manager: pip
          test-tool: pytest
      - publish